### ISSUE TITLE
CDW: DataViz Lab6 updates

### ISSUE THREAD

**Issue by kuldeepsahu1105** [mmehra12/HOLWorkshops#12]
<img width="1056" alt="image" src="https://github.com/user-attachments/assets/ca52bfeb-0d98-4dc5-a4c3-828dd34a8eb8">
Lab6 instructions and screenshots seems different than what we see after login and no dataset is visible for the workshop user. So unable to proceed on that lab.
<img width="1438" alt="image" src="https://github.com/user-attachments/assets/f264496d-c730-4b2c-b4b8-e503d960cacc">

**Comment by mmehra12** [comment]
As per the step, the user is supposed to click on the **Data** tab which is present in both the screenshots. So that should be ok.

As far as the "New Connection" not showing up for your user is probably because you have not added your user group to the Admin group while creating the Data Viz. That should take care of this issue. I've added this step to the instructor guide.
